FROM node:22.20.0-alpine3.22 AS build

ARG APP_VERSION=local
ENV APP_VERSION=${APP_VERSION}

WORKDIR /src
COPY frontend ./
RUN node build.mjs


FROM nginxinc/nginx-unprivileged:1.29.1-alpine AS runtime

COPY --chown=101:101 frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build --chown=101:101 /dist/ /usr/share/nginx/html/

USER 101:101
EXPOSE 8080
