apiVersion: v1
kind: ConfigMap
metadata:
  name: challenge-config
  labels:
    {{- include "devops-challenge.labels" . | nindent 4 }}
data:
  DB_HOST: mongodb
  DB_PORT: "27017"
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  LOG_LEVEL: INFO
