{{- if .Values.azureKeyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: challenge-key-vault
  labels:
    {{- include "devops-challenge.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "devops-challenge.secretName" . }}
      type: Opaque
      data:
        - objectName: {{ .Values.azureKeyVault.secretName | quote }}
          key: DB_PASSWORD
  parameters:
    usePodIdentity: "false"
    clientID: {{ required "azureKeyVault.workloadIdentityClientId is required" .Values.azureKeyVault.workloadIdentityClientId | quote }}
    keyvaultName: {{ required "azureKeyVault.name is required" .Values.azureKeyVault.name | quote }}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: {{ .Values.azureKeyVault.secretName }}
          objectType: secret
          objectVersion: ""
    tenantId: {{ required "azureKeyVault.tenantId is required" .Values.azureKeyVault.tenantId | quote }}
{{- end }}
