{{- if .Values.awsSecretsManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: challenge-key-vault
  labels:
    {{- include "devops-challenge.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider: aws

  secretObjects:
    - secretName: {{ include "devops-challenge.secretName" . }}
      type: Opaque
      data:
        - objectName: {{ .Values.awsSecretsManager.secretName | quote }}
          key: DB_PASSWORD

  parameters:
    region: {{ .Values.awsSecretsManager.region | quote }}
    usePodIdentity: "true"
    objects: |
      - objectName: {{ .Values.awsSecretsManager.secretName | quote }}
        objectType: "secretsmanager"
{{- end }}
