{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-challenge.secretName" . }}
  labels:
    {{- include "devops-challenge.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ required "secret.localPassword is required when secret.create=true" .Values.secret.localPassword | quote }}
{{- end }}
