{{- if .Values.azureKeyVault.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devops-challenge.serviceAccountName" . }}
  labels:
    {{- include "devops-challenge.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ required "azureKeyVault.workloadIdentityClientId is required" .Values.azureKeyVault.workloadIdentityClientId | quote }}
{{- end }}
