backend:
  image:
    repository: atharva038/devops-challenge-backend
    tag: 1.0.0-b15-b26a92af
    pullPolicy: Always
frontend:
  image:
    repository: atharva038/devops-challenge-frontend
    tag: 1.0.0-b15-b26a92af
    pullPolicy: Always
  service:
    type: LoadBalancer
database:
  persistence:
    enabled: true
    size: 8Gi
    storageClass: gp3
secret:
  create: false
  existingSecretName: challenge-db-secret
awsSecretsManager:
  enabled: true
  region: us-east-1
  secretName: devops-challenge-db-password
monitoring:
  enabled: true
  prometheusReleaseLabel: monitoring
